name: Run Python Hello World

on: push

jobs:
  python-hello:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo Print Hello World
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' 

    - name: Run python script
      run: python 1.hello.py