name: send email
on: push

jobs: 
  mail:
   runs-on: ubuntu-latest
   steps:
   - name: print hello world
     run: echo "hello world"  


   - name: sending email
     
     run: echo "hello email world"


     
    